### ISSUE TITLE
/scripts/pretrain.py

### ISSUE THREAD

**Issue by AlexFanC** [linqs/dickens-arxiv24#1]
Hello, sorry to bother you.
I found that '/scripts/pretrain.py' is missing in the citation task.

**Comment by cfpryor** [comment]
Hey Alex, not a bother at all!

Just a quick clarification on the citation task. There’s no need for a pretrain script for this experiment. The README was a bit unclear, so I’ve updated it for better clarity.

In summary, NeuPSL requires a neural component. Some experiments utilize the baseline neural model, while others use a pre-trained model (handled automatically after training). However, not all experiments require pretraining—for instance, the citation network doesn't. You can simply run /scripts/train.py for this experiment.

I'll close for now, but go ahead and respond if you need more help or it doesn't work!

**Comment by AlexFanC** [comment]
Thank you for your response
